import type { ProductCategory, Product } from "@/modules/shopping-agent/types";

export const MOCK_WEARABLE_CATEGORIES: ProductCategory[] = [
  { id: "cat-w-001", name: "Women's Clothing", slug: "womens-clothing", parentId: null, productCount: 124, mode: "wearable" },
  { id: "cat-w-002", name: "Men's Clothing",   slug: "mens-clothing",   parentId: null, productCount: 98,  mode: "wearable" },
  { id: "cat-w-003", name: "Shoes",            slug: "shoes",           parentId: null, productCount: 75,  mode: "wearable" },
  { id: "cat-w-004", name: "Accessories",      slug: "accessories",     parentId: null, productCount: 56,  mode: "wearable" },
  { id: "cat-w-005", name: "Sportswear",       slug: "sportswear",      parentId: null, productCount: 43,  mode: "wearable" },
];

export const MOCK_UNWEARABLE_CATEGORIES: ProductCategory[] = [
  { id: "cat-u-001", name: "Smartphones",      slug: "smartphones",     parentId: null, productCount: 62,  mode: "unwearable" },
  { id: "cat-u-002", name: "Laptops",          slug: "laptops",         parentId: null, productCount: 48,  mode: "unwearable" },
  { id: "cat-u-003", name: "Home Appliances",  slug: "home-appliances", parentId: null, productCount: 87,  mode: "unwearable" },
  { id: "cat-u-004", name: "Audio & Sound",    slug: "audio",           parentId: null, productCount: 34,  mode: "unwearable" },
  { id: "cat-u-005", name: "Kitchen",          slug: "kitchen",         parentId: null, productCount: 59,  mode: "unwearable" },
  { id: "cat-u-006", name: "Furniture",        slug: "furniture",       parentId: null, productCount: 41,  mode: "unwearable" },
];

export const MOCK_WEARABLE_PRODUCTS: Product[] = [
  {
    id: "p-w-001",
    name: "Floral Wrap Dress",
    description: "A beautiful floral wrap dress perfect for summer occasions.",
    price: 89.99,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400",
    categoryId: "cat-w-001",
    tags: ["dress", "floral", "summer"],
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    variants: [
      { id: "v-001-xs", label: "XS", value: "xs", type: "size", inStock: true },
      { id: "v-001-s",  label: "S",  value: "s",  type: "size", inStock: true },
      { id: "v-001-m",  label: "M",  value: "m",  type: "size", inStock: true },
      { id: "v-001-l",  label: "L",  value: "l",  type: "size", inStock: false },
    ],
  },
  {
    id: "p-w-002",
    name: "Classic Oxford Shirt",
    description: "Crisp cotton oxford shirt for a polished everyday look.",
    price: 59.99,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400",
    categoryId: "cat-w-002",
    tags: ["shirt", "classic", "office"],
    rating: 4.3,
    reviewCount: 94,
    inStock: true,
    variants: [
      { id: "v-002-s", label: "S",   value: "s",   type: "size", inStock: true },
      { id: "v-002-m", label: "M",   value: "m",   type: "size", inStock: true },
      { id: "v-002-l", label: "L",   value: "l",   type: "size", inStock: true },
      { id: "v-002-xl",label: "XL",  value: "xl",  type: "size", inStock: true },
    ],
  },
  {
    id: "p-w-003",
    name: "White Sneakers",
    description: "Clean minimalist sneakers for everyday wear.",
    price: 110.00,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
    categoryId: "cat-w-003",
    tags: ["sneakers", "white", "casual"],
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    variants: [
      { id: "v-003-39", label: "EU 39", value: "39", type: "size", inStock: true },
      { id: "v-003-40", label: "EU 40", value: "40", type: "size", inStock: true },
      { id: "v-003-41", label: "EU 41", value: "41", type: "size", inStock: true },
      { id: "v-003-42", label: "EU 42", value: "42", type: "size", inStock: false },
    ],
  },
  {
    id: "p-w-004",
    name: "Tailored Chino Pants",
    description: "Slim-tapered chinos in a soft cotton twill — dresses up or down with ease.",
    price: 79.99,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1720065359628-1a9d36822df7?w=400",
    categoryId: "cat-w-002",
    tags: ["chinos", "pants", "smart-casual"],
    rating: 4.4,
    reviewCount: 76,
    inStock: true,
    variants: [
      { id: "v-004-30", label: "W30", value: "30", type: "size", inStock: true },
      { id: "v-004-32", label: "W32", value: "32", type: "size", inStock: true },
      { id: "v-004-34", label: "W34", value: "34", type: "size", inStock: true },
      { id: "v-004-36", label: "W36", value: "36", type: "size", inStock: true },
    ],
  },
  {
    id: "p-w-005",
    name: "Tailored Wool Blazer",
    description: "A structured, single-breasted blazer that elevates any business or evening look.",
    price: 249.99,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1539114756097-bd88be4fa7f4?w=400",
    categoryId: "cat-w-002",
    tags: ["blazer", "business", "formal"],
    rating: 4.8,
    reviewCount: 152,
    inStock: true,
    variants: [
      { id: "v-005-s", label: "S", value: "s", type: "size", inStock: true },
      { id: "v-005-m", label: "M", value: "m", type: "size", inStock: true },
      { id: "v-005-l", label: "L", value: "l", type: "size", inStock: true },
      { id: "v-005-xl", label: "XL", value: "xl", type: "size", inStock: false },
    ],
  },
  {
    id: "p-w-006",
    name: "Essential Crew T-Shirt",
    description: "A perfectly weighted crew-neck tee in premium combed cotton.",
    price: 34.99,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1618677603286-0ec56cb6e1b5?w=400",
    categoryId: "cat-w-002",
    tags: ["tshirt", "casual", "essential"],
    rating: 4.6,
    reviewCount: 341,
    inStock: true,
    variants: [
      { id: "v-006-s", label: "S", value: "s", type: "size", inStock: true },
      { id: "v-006-m", label: "M", value: "m", type: "size", inStock: true },
      { id: "v-006-l", label: "L", value: "l", type: "size", inStock: true },
      { id: "v-006-xl", label: "XL", value: "xl", type: "size", inStock: true },
    ],
  },
  {
    id: "p-w-007",
    name: "Slim Straight Jeans",
    description: "Mid-wash denim with a touch of stretch for an easy, everyday fit.",
    price: 89.99,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1746289352064-36b2deb0bc08?w=400",
    categoryId: "cat-w-002",
    tags: ["jeans", "denim", "casual"],
    rating: 4.5,
    reviewCount: 198,
    inStock: true,
    variants: [
      { id: "v-007-30", label: "W30", value: "30", type: "size", inStock: true },
      { id: "v-007-32", label: "W32", value: "32", type: "size", inStock: true },
      { id: "v-007-34", label: "W34", value: "34", type: "size", inStock: true },
      { id: "v-007-36", label: "W36", value: "36", type: "size", inStock: false },
    ],
  },
  {
    id: "p-w-008",
    name: "Leather Derby Shoes",
    description: "Hand-finished leather derbies with a cushioned sole for all-day comfort.",
    price: 159.99,
    currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1563434194539-fcc823f9bf92?w=400",
    categoryId: "cat-w-003",
    tags: ["shoes", "leather", "formal"],
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    variants: [
      { id: "v-008-40", label: "EU 40", value: "40", type: "size", inStock: true },
      { id: "v-008-41", label: "EU 41", value: "41", type: "size", inStock: true },
      { id: "v-008-42", label: "EU 42", value: "42", type: "size", inStock: true },
      { id: "v-008-43", label: "EU 43", value: "43", type: "size", inStock: true },
    ],
  },
];

export const MOCK_UNWEARABLE_PRODUCTS: Product[] = [
  // ── Smartphones ──────────────────────────────────────────────────────────
  {
    id: "p-u-001",
    name: "iPhone 16 Pro",
    description: "Apple's latest flagship with titanium design and A18 Pro chip.",
    price: 1199.00, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400",
    categoryId: "cat-u-001", tags: ["apple", "smartphone", "flagship"],
    rating: 4.9, reviewCount: 1024, inStock: true,
    variants: [
      { id: "v-u001-128", label: "128 GB", value: "128", type: "style", inStock: true },
      { id: "v-u001-256", label: "256 GB", value: "256", type: "style", inStock: true },
    ],
  },
  {
    id: "p-u-010",
    name: "Samsung Galaxy S25 Ultra",
    description: "Android flagship with 200MP camera and built-in S Pen.",
    price: 1299.00, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400",
    categoryId: "cat-u-001", tags: ["samsung", "android", "flagship"],
    rating: 4.7, reviewCount: 832, inStock: true,
    variants: [
      { id: "v-u010-256", label: "256 GB", value: "256", type: "style", inStock: true },
      { id: "v-u010-512", label: "512 GB", value: "512", type: "style", inStock: true },
    ],
  },
  // ── Laptops ───────────────────────────────────────────────────────────────
  {
    id: "p-u-002",
    name: "MacBook Air M3",
    description: "Ultra-thin laptop with Apple Silicon and all-day battery life.",
    price: 1299.00, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400",
    categoryId: "cat-u-002", tags: ["apple", "laptop", "ultrabook"],
    rating: 4.8, reviewCount: 672, inStock: true,
    variants: [
      { id: "v-u002-8",  label: "8 GB RAM",  value: "8",  type: "style", inStock: true },
      { id: "v-u002-16", label: "16 GB RAM", value: "16", type: "style", inStock: true },
    ],
  },
  {
    id: "p-u-011",
    name: "Dell XPS 15 OLED",
    description: "Premium Windows laptop with 4K OLED display and Intel Core Ultra.",
    price: 1799.00, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400",
    categoryId: "cat-u-002", tags: ["dell", "windows", "oled", "laptop"],
    rating: 4.6, reviewCount: 389, inStock: true,
    variants: [
      { id: "v-u011-16", label: "16 GB / 512 GB SSD", value: "16", type: "style", inStock: true },
      { id: "v-u011-32", label: "32 GB / 1 TB SSD",   value: "32", type: "style", inStock: true },
    ],
  },
  // ── Audio ─────────────────────────────────────────────────────────────────
  {
    id: "p-u-003",
    name: "Sony WH-1000XM5",
    description: "Industry-leading noise cancelling headphones with clear sound.",
    price: 349.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
    categoryId: "cat-u-004", tags: ["sony", "headphones", "noise-cancelling"],
    rating: 4.6, reviewCount: 445, inStock: true,
    variants: [
      { id: "v-u003-black",  label: "Black",  value: "black",  type: "color", inStock: true },
      { id: "v-u003-silver", label: "Silver", value: "silver", type: "color", inStock: true },
    ],
  },
  {
    id: "p-u-012",
    name: "AirPods Pro 2",
    description: "Apple ANC earbuds with Adaptive Audio and USB-C charging.",
    price: 249.00, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1603351154351-5e2d0600bb77?w=400",
    categoryId: "cat-u-004", tags: ["apple", "earbuds", "anc", "wireless"],
    rating: 4.8, reviewCount: 2104, inStock: true,
    variants: [{ id: "v-u012-wh", label: "White", value: "white", type: "color", inStock: true }],
  },
  // ── Home & Appliances ─────────────────────────────────────────────────────
  {
    id: "p-u-004",
    name: "Dyson V15 Detect",
    description: "Powerful cordless vacuum with laser dust detection technology.",
    price: 749.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400",
    categoryId: "cat-u-003", tags: ["dyson", "vacuum", "cordless"],
    rating: 4.4, reviewCount: 312, inStock: true,
    variants: [{ id: "v-u004-abs", label: "Absolute", value: "absolute", type: "style", inStock: true }],
  },
  {
    id: "p-u-013",
    name: "Instant Pot Duo 7-in-1",
    description: "Versatile pressure cooker, slow cooker, rice cooker and more.",
    price: 99.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400",
    categoryId: "cat-u-003", tags: ["kitchen", "pressure-cooker", "appliance"],
    rating: 4.7, reviewCount: 5830, inStock: true,
    variants: [
      { id: "v-u013-6qt",  label: "6 Qt",  value: "6",  type: "style", inStock: true },
      { id: "v-u013-8qt",  label: "8 Qt",  value: "8",  type: "style", inStock: true },
    ],
  },
  // ── Networking ────────────────────────────────────────────────────────────
  {
    id: "p-u-020",
    name: "TP-Link Deco XE75 (3-Pack)",
    description: "WiFi 6E Mesh system covering up to 6,000 sq ft with tri-band.",
    price: 299.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400",
    categoryId: "cat-u-005", tags: ["networking", "wifi", "mesh", "router"],
    rating: 4.7, reviewCount: 1243, inStock: true,
    variants: [{ id: "v-u020-3", label: "3-Pack", value: "3", type: "style", inStock: true }],
  },
  {
    id: "p-u-021",
    name: "Netgear Nighthawk RAX50",
    description: "AX5400 WiFi 6 router with 6 streams and MU-MIMO technology.",
    price: 179.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1563770660941-20978e870e26?w=400",
    categoryId: "cat-u-005", tags: ["networking", "wifi", "router", "wifi6"],
    rating: 4.5, reviewCount: 874, inStock: true,
    variants: [{ id: "v-u021-std", label: "Standard", value: "std", type: "style", inStock: true }],
  },
  {
    id: "p-u-022",
    name: "TP-Link 8-Port Gigabit Switch",
    description: "Unmanaged network switch with Gigabit Ethernet and plug-and-play setup.",
    price: 29.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400",
    categoryId: "cat-u-005", tags: ["networking", "switch", "ethernet", "lan"],
    rating: 4.6, reviewCount: 3200, inStock: true,
    variants: [{ id: "v-u022-std", label: "8-Port", value: "8", type: "style", inStock: true }],
  },
  // ── Home Office ───────────────────────────────────────────────────────────
  {
    id: "p-u-030",
    name: "LG 27UK850 4K Monitor",
    description: "27-inch 4K UHD IPS monitor with USB-C and HDR10 support.",
    price: 449.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400",
    categoryId: "cat-u-006", tags: ["monitor", "4k", "home-office", "lg"],
    rating: 4.6, reviewCount: 1087, inStock: true,
    variants: [{ id: "v-u030-std", label: "27\"", value: "27", type: "style", inStock: true }],
  },
  {
    id: "p-u-031",
    name: "Logitech MX Keys Combo",
    description: "Wireless keyboard and MX Master 3S mouse — the ultimate desk setup.",
    price: 199.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400",
    categoryId: "cat-u-006", tags: ["keyboard", "mouse", "combo", "wireless", "home-office"],
    rating: 4.8, reviewCount: 2341, inStock: true,
    variants: [
      { id: "v-u031-mac", label: "Mac Layout", value: "mac",  type: "style", inStock: true },
      { id: "v-u031-win", label: "Windows",    value: "win",  type: "style", inStock: true },
    ],
  },
  {
    id: "p-u-032",
    name: "Elgato Key Light Air",
    description: "Professional LED panel light for streaming and video calls.",
    price: 99.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400",
    categoryId: "cat-u-006", tags: ["lighting", "streaming", "home-office", "elgato"],
    rating: 4.7, reviewCount: 678, inStock: true,
    variants: [{ id: "v-u032-std", label: "Standard", value: "std", type: "style", inStock: true }],
  },
  // ── Gaming ────────────────────────────────────────────────────────────────
  {
    id: "p-u-040",
    name: "Razer BlackShark V2 Pro",
    description: "Wireless gaming headset with THX Spatial Audio and 70hr battery.",
    price: 179.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1599669454699-248893623440?w=400",
    categoryId: "cat-u-007", tags: ["gaming", "headset", "razer", "wireless"],
    rating: 4.6, reviewCount: 932, inStock: true,
    variants: [
      { id: "v-u040-blk", label: "Black", value: "black", type: "color", inStock: true },
      { id: "v-u040-wht", label: "White", value: "white", type: "color", inStock: true },
    ],
  },
  {
    id: "p-u-041",
    name: "Logitech G Pro X Superlight 2",
    description: "25K DPI lightweight gaming mouse at just 60g for pro-level play.",
    price: 159.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
    categoryId: "cat-u-007", tags: ["gaming", "mouse", "logitech", "esports"],
    rating: 4.8, reviewCount: 1456, inStock: true,
    variants: [
      { id: "v-u041-blk", label: "Black", value: "black", type: "color", inStock: true },
      { id: "v-u041-wht", label: "White", value: "white", type: "color", inStock: true },
    ],
  },
  {
    id: "p-u-042",
    name: "Samsung Odyssey G7 34\" Curved",
    description: "Curved WQHD 165Hz gaming monitor with 1ms response time.",
    price: 699.99, currency: "USD",
    imageUrl: "https://images.unsplash.com/photo-1616763355548-1b606f439f86?w=400",
    categoryId: "cat-u-007", tags: ["gaming", "monitor", "curved", "samsung"],
    rating: 4.7, reviewCount: 768, inStock: true,
    variants: [{ id: "v-u042-std", label: "34\"", value: "34", type: "style", inStock: true }],
  },
];

export async function getMockCategories(mode: "wearable" | "unwearable"): Promise<ProductCategory[]> {
  await new Promise((r) => setTimeout(r, 200));
  return mode === "wearable" ? MOCK_WEARABLE_CATEGORIES : MOCK_UNWEARABLE_CATEGORIES;
}

export async function getMockProducts(categoryId?: string): Promise<Product[]> {
  await new Promise((r) => setTimeout(r, 250));
  const all = [...MOCK_WEARABLE_PRODUCTS, ...MOCK_UNWEARABLE_PRODUCTS];
  return categoryId ? all.filter((p) => p.categoryId === categoryId) : all;
}
