// `main.tsx` imports the compiled Tailwind output as raw text (see scripts/build-widget.mjs's
// esbuild `.css` -> `text` loader). This is a build artifact regenerated by `pnpm build:widget`
// before every build; this declaration just keeps `tsc --noEmit` happy about the import shape.
declare module "*.css" {
  const content: string;
  export default content;
}
